backend:
  name: git-gateway
  branch: master

media_folder: src/img
public_folder: /img

collections:

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "heroImage", widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/student-hotels-it/src/static/img/"}}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Hero Image", name: "heroImage", widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/student-hotels-it/src/static/img/"}}
          - {label: Mosaic, name: "mosaic", widget: object, fields: [{label: Title, name: title, widget: string}, {label: Subtitle, name: subtitle, widget: string} ]}
          - {label: Posts, name: "posts", widget: object, fields: [{label: Title, name: title, widget: string}, {label: Subtitle, name: subtitle, widget: string} ]}
          - {label: "Newsletter Image", name: "newsletterImage", widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/student-hotels-it/src/static/img/"}}


      - file: "src/pages/blog/index.md"
        label: "Home Blog"
        name: "homeblog"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-blog"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Image", name: "heroImage", widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/student-hotels-it/src/static/img/"}}
      - file: "src/pages/tags/index.md"
        label: "Home Tags"
        name: "hometags"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-tags"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Image", name: "heroImage", widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/student-hotels-it/src/static/img/"}}
      - file: "src/pages/chi-siamo/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Hero Image", name: "heroImage", widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/student-hotels-it/src/static/img/"}}
      - file: "src/pages/mission/index.md"
        label: "Mission"
        name: "mission"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "mission-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero", name: heroImage, widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/student-hotels-it/src/static/img/"}
          - {label: Heading, name: heading, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text} ]}
          - {label: Block With Image, name: block1, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image, name: image, widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/student-hotels-it/src/static/img/"} ]}
          - {label: Block With Image, name: block2, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image, name: image, widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/student-hotels-it/src/static/img/" } ]}
          - {label: Board, name: board, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text} ]}
          - {label: Block With Image, name: block3, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image, name: image, widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/student-hotels-it/src/static/img/"} ]}
      - file: "src/pages/faq/index.md"
        label: "Faq"
        name: "faq"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Image, name: "heroImage", widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/student-hotels-it/src/static/img/"}}
          - {label: Heading, name: heading, widget: string}
          - {label: faq, name: faq, widget: list, fields: [{label: Question, name: question, widget: string}, {label: Answer, name: answer, widget: text}]}

  - name: "hotels"
    label: "Hotels"
    folder: "src/pages/hotels"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "hotel-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Heading", name: "heading", widget: "string"}
      - {label: "TravelPayout hotelId", name: "hotelId", widget: "string"}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "Hotel Info", name: "body", widget: "markdown"}
      - {label: "Facilities", name: "facilities", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "legals"
    label: "Legals"
    folder: "src/pages/note-legali"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hero Image", name: "heroImage", widget: custompathimage, customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/filippoferri/student-hotels-it/src/static/img/"}}
      - {label: "Body", name: "body", widget: "markdown"}



